"""Add item variant fields (size, color, quantity)

Revision ID: 35d5e463fe94
Revises: 7bdde8971fcd
Create Date: 2026-01-04 11:15:56.029876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d5e463fe94'
down_revision = '7bdde8971fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('quantity')
        batch_op.drop_column('color')
        batch_op.drop_column('size')

    # ### end Alembic commands ###
