"""Initial migration with PriceHistory

Revision ID: 3bf7272ee759
Revises:
Create Date: 2026-01-05 00:30:26.932885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf7272ee759'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_extraction_log',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('domain', sa.String(length=255), nullable=False),
                    sa.Column('url', sa.String(length=2048), nullable=True),
                    sa.Column('success', sa.Boolean(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=True),
                    sa.Column('extraction_method', sa.String(length=50), nullable=True),
                    sa.Column('error_type', sa.String(length=50), nullable=True),
                    sa.Column('response_time_ms', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('price_extraction_log', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_price_extraction_log_created_at'),
            ['created_at'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_price_extraction_log_domain'),
            ['domain'],
            unique=False)

    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=20), nullable=False),
                    sa.Column('email', sa.String(length=50), nullable=False),
                    sa.Column('is_private', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('event',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('created_by_id', sa.Integer(), nullable=False),
                    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('notification',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('message', sa.String(length=500), nullable=False),
                    sa.Column('link', sa.String(length=500), nullable=False),
                    sa.Column('is_read', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(
            'idx_notif_user_unread', [
                'user_id', 'is_read'], unique=False)

    op.create_table('item',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('description', sa.String(length=750), nullable=False),
                    sa.Column('link', sa.String(length=2048), nullable=True),
                    sa.Column('comment', sa.String(length=100), nullable=True),
                    sa.Column('price', sa.Float(), nullable=True),
                    sa.Column('status', sa.String(length=20), nullable=False),
                    sa.Column('question', sa.String(length=100), nullable=True),
                    sa.Column('year', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('category', sa.String(length=50), nullable=True),
                    sa.Column('image_url', sa.String(length=2048), nullable=True),
                    sa.Column('priority', sa.String(length=50), nullable=True),
                    sa.Column('last_updated_by_id', sa.Integer(), nullable=True),
                    sa.Column('event_id', sa.Integer(), nullable=True),
                    sa.Column('price_updated_at', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('size', sa.String(length=50), nullable=True),
                    sa.Column('color', sa.String(length=50), nullable=True),
                    sa.Column('quantity', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
                    sa.ForeignKeyConstraint(['last_updated_by_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(
            'idx_item_user_status', [
                'user_id', 'status'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_item_category'),
            ['category'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_item_event_id'),
            ['event_id'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_item_priority'),
            ['priority'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_item_status'),
            ['status'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_item_user_id'),
            ['user_id'],
            unique=False)

    op.create_table('comment',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.String(length=500), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('item_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(
            'idx_comment_item', [
                'item_id', 'created_at'], unique=False)

    op.create_table('contributions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('item_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('is_organizer', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('item_id', 'user_id', name='unique_contribution')
                    )
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_contributions_item_id'),
            ['item_id'],
            unique=False)

    op.create_table('price_history',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('item_id', sa.Integer(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('recorded_at', sa.DateTime(), nullable=True),
                    sa.Column('source', sa.String(length=50), nullable=True),
                    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(
            'idx_price_history_item_date', [
                'item_id', 'recorded_at'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_price_history_item_id'),
            ['item_id'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_price_history_recorded_at'),
            ['recorded_at'],
            unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_price_history_item_id'))
        batch_op.drop_index('idx_price_history_item_date')

    op.drop_table('price_history')
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contributions_item_id'))

    op.drop_table('contributions')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index('idx_comment_item')

    op.drop_table('comment')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_user_id'))
        batch_op.drop_index(batch_op.f('ix_item_status'))
        batch_op.drop_index(batch_op.f('ix_item_priority'))
        batch_op.drop_index(batch_op.f('ix_item_event_id'))
        batch_op.drop_index(batch_op.f('ix_item_category'))
        batch_op.drop_index('idx_item_user_status')

    op.drop_table('item')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('idx_notif_user_unread')

    op.drop_table('notification')
    op.drop_table('event')
    op.drop_table('user')
    with op.batch_alter_table('price_extraction_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_extraction_log_domain'))
        batch_op.drop_index(batch_op.f('ix_price_extraction_log_created_at'))

    op.drop_table('price_extraction_log')
    # ### end Alembic commands ###
