"""add last updated_by to item

Revision ID: 45a27577af4d
Revises: 38b2adc6e0f6
Create Date: 2023-11-27 11:03:10.486625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a27577af4d'
down_revision = '38b2adc6e0f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['last_updated_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_updated_by_id')

    # ### end Alembic commands ###
