"""empty message

Revision ID: 699a28e2325d
Revises: 7620e2a8e127
Create Date: 2023-11-29 09:12:28.165488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699a28e2325d'
down_revision = '7620e2a8e127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
