"""Increase link and image_url column sizes to 2048 for long URLs

Revision ID: 78ea68cde3a6
Revises: 9f8c7b6a5d4e
Create Date: 2025-11-09 19:02:35.688194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ea68cde3a6'
down_revision = '9f8c7b6a5d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2048),
               existing_nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2048),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('link',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
