"""Add indexes for performance

Revision ID: 80bf6accc0b7
Revises: 5eccc51abd8f
Create Date: 2025-10-16 21:10:55.938100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80bf6accc0b7'
down_revision = '5eccc51abd8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index('idx_item_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_user_id'))
        batch_op.drop_index(batch_op.f('ix_item_status'))
        batch_op.drop_index(batch_op.f('ix_item_priority'))
        batch_op.drop_index(batch_op.f('ix_item_category'))
        batch_op.drop_index('idx_item_user_status')

    # ### end Alembic commands ###
