"""Add Event model, event_id and price_updated_at to Item

Revision ID: 858a27dc5d01
Revises: 78ea68cde3a6
Create Date: 2025-12-28 18:58:11.459983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858a27dc5d01'
down_revision = '78ea68cde3a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price_updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_item_event_id'), ['event_id'], unique=False)
        batch_op.create_foreign_key('fk_item_event_id', 'event', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_item_event_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_item_event_id'))
        batch_op.drop_column('price_updated_at')
        batch_op.drop_column('event_id')

    op.drop_table('event')
    # ### end Alembic commands ###
